
title: My Resume
url: 'https://jviera.github.io'
baseurl: '/jviera.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: José Viera
tagline: Programador Java
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jviera.dev@gmail.com
phone: 722 290 72 81
website: jviera.github.io #do not add http://
linkedin: josé-barbarito-viera-rebolledo-905b0850
github: jviera
twitter: '@jvieradev'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
